defaults:
  role: research
  machine_role: pc1
  scheduler_enabled: false
  sync_enabled: false

environments:
  development:
    role: research
    machine_role: pc1
    scheduler_enabled: false
    sync_enabled: false
  deploy:
    role: deploy
    machine_role: pc2
    scheduler_enabled: true
    sync_enabled: true
